INSERT INTO `HOLIDAYS` (`DAY`,`REASON`,`TYPE`,`CREATED_AT`, `CREATED_BY`)
 VALUES (' JAN 1, 2025 ', 'NEW YEAR''S DAY', 'FESTIVAL', CURDATE(), 'DBA');

INSERT INTO `HOLIDAYS` (`DAY`,`REASON`,`TYPE`,`CREATED_AT`, `CREATED_BY`)
 VALUES (' JAN 26, 2025 ', 'REPUBLIC DAY', 'FEDERAL', CURDATE(), 'DBA');

INSERT INTO `HOLIDAYS` (`DAY`,`REASON`,`TYPE`,`CREATED_AT`, `CREATED_BY`)
 VALUES (' APRIL 14, 2025 ', 'DR. B.R. AMBEDKAR JAYANTI', 'FEDERAL', CURDATE(), 'DBA');

INSERT INTO `HOLIDAYS` (`DAY`,`REASON`,`TYPE`,`CREATED_AT`, `CREATED_BY`)
 VALUES (' MAY 1, 2025 ', 'LABOUR''S DAY', 'FEDERAL', CURDATE(), 'DBA');

INSERT INTO `HOLIDAYS` (`DAY`,`REASON`,`TYPE`,`CREATED_AT`, `CREATED_BY`)
 VALUES (' AUGUST 15, 2025 ', 'INDEPENDENCE DAY', 'FEDERAL', CURDATE(), 'DBA');

INSERT INTO `HOLIDAYS` (`DAY`,`REASON`,`TYPE`,`CREATED_AT`, `CREATED_BY`)
 VALUES (' OCTOBER 2, 2025 ', 'MAHATMA GANDHI JAYANTI', 'FEDERAL', CURDATE(), 'DBA');

INSERT INTO `HOLIDAYS` (`DAY`,`REASON`,`TYPE`,`CREATED_AT`, `CREATED_BY`)
 VALUES (' OCTOBER 20, 2025 ', 'DIWALI','FESTIVAL', CURDATE(), 'DBA');

INSERT INTO `HOLIDAYS` (`DAY`,`REASON`,`TYPE`,`CREATED_AT`, `CREATED_BY`)
  VALUES (' DECEMBER 25, 2025 ', 'CHRISTMAS DAY', 'FESTIVAL', CURDATE(), 'DBA');

INSERT INTO `ROLES` (`ROLE_NAME`,`CREATED_AT`, `CREATED_BY`)
  VALUES ('ADMIN',CURDATE(),'DBA');

INSERT INTO `ROLES` (`ROLE_NAME`,`CREATED_AT`, `CREATED_BY`)
  VALUES ('STUDENT',CURDATE(),'DBA');