CREATE TABLE IF NOT EXISTS `CONTACT_MSG` (
  `CONTACT_ID` INT AUTO_INCREMENT  PRIMARY KEY,
  `NAME` VARCHAR(100) NOT NULL,
  `MOBILE_NUM` VARCHAR(10) NOT NULL,
  `EMAIL` VARCHAR(100) NOT NULL,
  `SUBJECT` VARCHAR(100) NOT NULL,
  `MESSAGE` VARCHAR(500) NOT NULL,
  `STATUS` VARCHAR(10) NOT NULL,
  `CREATED_AT` TIMESTAMP NOT NULL,
  `CREATED_BY` VARCHAR(50) NOT NULL,
  `UPDATED_AT` TIMESTAMP DEFAULT NULL,
  `UPDATED_BY` VARCHAR(50) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS `HOLIDAYS` (
  `DAY` VARCHAR(20) NOT NULL,
  `REASON` VARCHAR(100) NOT NULL,
  `TYPE` VARCHAR(20) NOT NULL,
  `CREATED_AT` TIMESTAMP NOT NULL,
  `CREATED_BY` VARCHAR(50) NOT NULL,
  `UPDATED_AT` TIMESTAMP DEFAULT NULL,
  `UPDATED_BY` VARCHAR(50) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS `ROLES` (
  `ROLE_ID` INT NOT NULL AUTO_INCREMENT,
  `ROLE_NAME` VARCHAR(50) NOT NULL,
  `CREATED_AT` TIMESTAMP NOT NULL,
  `CREATED_BY` VARCHAR(50) NOT NULL,
  `UPDATED_AT` TIMESTAMP DEFAULT NULL,
  `UPDATED_BY` VARCHAR(50) DEFAULT NULL,
   PRIMARY KEY (`ROLE_ID`)
);

CREATE TABLE IF NOT EXISTS `ADDRESS` (
  `ADDRESS_ID` INT NOT NULL AUTO_INCREMENT,
  `ADDRESS1` VARCHAR(200) NOT NULL,
  `ADDRESS2` VARCHAR(200) DEFAULT NULL,
  `CITY` VARCHAR(50) NOT NULL,
  `STATE` VARCHAR(50) NOT NULL,
  `ZIP_CODE` INT NOT NULL,
  `CREATED_AT` TIMESTAMP NOT NULL,
  `CREATED_BY` VARCHAR(50) NOT NULL,
  `UPDATED_AT` TIMESTAMP DEFAULT NULL,
  `UPDATED_BY` VARCHAR(50) DEFAULT NULL,
   PRIMARY KEY (`ADDRESS_ID`)
);

CREATE TABLE IF NOT EXISTS `PERSON` (
  `PERSON_ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NOT NULL,
  `EMAIL` VARCHAR(50) NOT NULL,
  `MOBILE_NUMBER` VARCHAR(20) NOT NULL,
  `PWD` VARCHAR(200) NOT NULL,
  `ROLE_ID` INT NOT NULL,
  `ADDRESS_ID` INT NULL,
  `CREATED_AT` TIMESTAMP NOT NULL,
  `CREATED_BY` VARCHAR(50) NOT NULL,
  `UPDATED_AT` TIMESTAMP DEFAULT NULL,
  `UPDATED_BY` VARCHAR(50) DEFAULT NULL,
   PRIMARY KEY (`PERSON_ID`),
   FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ROLE_ID),
   FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID)
);

CREATE TABLE IF NOT EXISTS `class` (
    `class_id` int NOT NULL AUTO_INCREMENT,
    `name` varchar(100) NOT NULL,
    `created_at` TIMESTAMP NOT NULL,
    `created_by` varchar(50) NOT NULL,
    `updated_at` TIMESTAMP DEFAULT NULL,
    `updated_by` varchar(50) DEFAULT NULL,
    PRIMARY KEY (`class_id`)
    );

ALTER TABLE `person`
ADD COLUMN `class_id` int NULL AFTER `address_id`,
ADD CONSTRAINT `FK_CLASS_CLASS_ID` FOREIGN KEY (`class_id`)
REFERENCES `class`(`class_id`);

CREATE TABLE IF NOT EXISTS `courses` (
    `course_id` int NOT NULL AUTO_INCREMENT,
    `name` varchar(100) NOT NULL,
    `fees` varchar(10) NOT NULL,
    `created_at` TIMESTAMP NOT NULL,
    `created_by` varchar(50) NOT NULL,
    `updated_at` TIMESTAMP DEFAULT NULL,
    `updated_by` varchar(50) DEFAULT NULL,
    PRIMARY KEY (`course_id`)
    );

CREATE TABLE IF NOT EXISTS `person_courses` (
    `person_id` int NOT NULL,
    `course_id` int NOT NULL,
    FOREIGN KEY (person_id) REFERENCES person(person_id),
    FOREIGN KEY (course_id) REFERENCES courses(course_id),
    PRIMARY KEY (`person_id`,`course_id`)
    );