CREATE TABLE IF NOT EXISTS `CONTACT_MSG` (
  `CONTACT_ID` INT AUTO_INCREMENT  PRIMARY KEY,
  `NAME` VARCHAR(100) NOT NULL,
  `MOBILE_NUM` VARCHAR(10) NOT NULL,
  `EMAIL` VARCHAR(100) NOT NULL,
  `SUBJECT` VARCHAR(100) NOT NULL,
  `MESSAGE` VARCHAR(500) NOT NULL,
  `STATUS` VARCHAR(10) NOT NULL,
  `CREATED_AT` TIMESTAMP NOT NULL,
  `CREATED_BY` VARCHAR(50) NOT NULL,
  `UPDATED_AT` TIMESTAMP DEFAULT NULL,
  `UPDATED_BY` VARCHAR(50) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS `HOLIDAYS` (
  `DAY` VARCHAR(20) NOT NULL,
  `REASON` VARCHAR(100) NOT NULL,
  `TYPE` VARCHAR(20) NOT NULL,
  `CREATED_AT` TIMESTAMP NOT NULL,
  `CREATED_BY` VARCHAR(50) NOT NULL,
  `UPDATED_AT` TIMESTAMP DEFAULT NULL,
  `UPDATED_BY` VARCHAR(50) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS `ROLES` (
  `ROLE_ID` INT NOT NULL AUTO_INCREMENT,
  `ROLE_NAME` VARCHAR(50) NOT NULL,
  `CREATED_AT` TIMESTAMP NOT NULL,
  `CREATED_BY` VARCHAR(50) NOT NULL,
  `UPDATED_AT` TIMESTAMP DEFAULT NULL,
  `UPDATED_BY` VARCHAR(50) DEFAULT NULL,
   PRIMARY KEY (`ROLE_ID`)
);

CREATE TABLE IF NOT EXISTS `ADDRESS` (
  `ADDRESS_ID` INT NOT NULL AUTO_INCREMENT,
  `ADDRESS1` VARCHAR(200) NOT NULL,
  `ADDRESS2` VARCHAR(200) DEFAULT NULL,
  `CITY` VARCHAR(50) NOT NULL,
  `STATE` VARCHAR(50) NOT NULL,
  `ZIP_CODE` INT NOT NULL,
  `CREATED_AT` TIMESTAMP NOT NULL,
  `CREATED_BY` VARCHAR(50) NOT NULL,
  `UPDATED_AT` TIMESTAMP DEFAULT NULL,
  `UPDATED_BY` VARCHAR(50) DEFAULT NULL,
   PRIMARY KEY (`ADDRESS_ID`)
);

CREATE TABLE IF NOT EXISTS `PERSON` (
  `PERSON_ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NOT NULL,
  `EMAIL` VARCHAR(50) NOT NULL,
  `MOBILE_NUMBER` VARCHAR(20) NOT NULL,
  `PWD` VARCHAR(200) NOT NULL,
  `ROLE_ID` INT NOT NULL,
  `ADDRESS_ID` INT NULL,
  `CREATED_AT` TIMESTAMP NOT NULL,
  `CREATED_BY` VARCHAR(50) NOT NULL,
  `UPDATED_AT` TIMESTAMP DEFAULT NULL,
  `UPDATED_BY` VARCHAR(50) DEFAULT NULL,
   PRIMARY KEY (`PERSON_ID`),
   FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ROLE_ID),
   FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID)
);